### ISSUE TITLE
Does this package work on Umbraco Cloud?

### ISSUE THREAD

**Issue by raimondkempees-arc** [UmbHost/UmbHost.Cloudflare.Purge#6]
Hi, 

We're evaluating Umbraco Cloud and we're wondering whether this package works there?

Thanks,

Rai

**Comment by AaronSadlerUK** [comment]
Hi Rai,

Unfortunately not as they do not offer access to the API which is required.

It would work with our hosting (https://umbhost.net) if you were to use your own Cloudflare account
